### ISSUE TITLE
v3.0 KV Protocol Proposal: Add a `GetVersion` and `GetMetrics` gRPC endpoint

### ISSUE THREAD

**Issue by kennytm** [tikv/importer#4]
```proto
service ImportKV {
    rpc GetVersion(GetVersionRequest) returns (GetVersionResponse) {}
    rpc GetMetrics(GetMetricsRequest) returns (GetMetricsResponse) {}
}

message GetVersionResponse {
    string version = 1;
}

message GetMetricsResponse {
    // To be determined
}
```

The GetVersion API will be used to determine whether new APIs will be available.

The GetMetrics API will be used by Lightning to report import progress to the log and web interface (refer to debugpb implementation in TiKV).

**Comment by kennytm** [comment]
Note: An alternative to a gRPC endpoint is to expose HTTP APIs.

**Comment by lance6716** [comment]
Could we close this issue?

**Comment by kennytm** [comment]
Done. In the future if you write `Fix #NNN` in the PR description it would close the issue #NNN automatically.
