### ISSUE TITLE
Failed to start importer

### ISSUE THREAD

**Issue by amyangfei** [tikv/importer#63]
## Bug Report

**What version of TiKV Importer are you using?**

TODO

**What operating system and CPU are you using?**

**What did you do?**

**What did you expect to see?**

**What did you see instead?**

```
[2020/05/18 14:40:16.552 +08:00] [FATAL] [setup.rs:118] ["failed to start memory monitor: Error: descriptor Desc { fq_name: \"process_virtual_memory_bytes\", help: \"Virtual memory size in bytes.\", const_label_pairs: [], variable_labels: [], id: 11660941
70200363441, dim_hash: 18077976125237009095 } already exists with the same fully-qualified name and const label values"]
```

**Comment by Minorli** [comment]
version: v4.0.0-rc.2
Deploy Method：Fresh Deploy,deploy the tidb cluster and lightning/importer at the same time.
Log detail:[2020/05/18 14:40:16.552 +08:00] [FATAL] [setup.rs:118] ["failed to start memory monitor: Error: descriptor Desc { fq_name: \"process_virtual_memory_bytes\", help: \"Virtual memory size in bytes.\", const_label_pairs: [], variable_labels: [], id: 11660941
70200363441, dim_hash: 18077976125237009095 } already exists with the same fully-qualified name and const label values"]
